package com.shuowen.yuzong.PinyinTest;

/**
 * 数组里出现了所有拼音的组合
 * */

public class Testpinyin
{
    static String[] s =
            {"a", "ya", "e", "sha", "ai", "yi", "an", "han", "ang", "ao", "wa", "niu", "yu", "ba", "pa", "pi", "bai", "bo", "bei", "ban", "pan", "bang", "beng", "pang", "bao", "bu", "pu", "po", "ben", "bi", "bian", "pian", "fan", "pin", "biao", "huo", "shao", "piao", "bie", "bin", "bing", "fou", "ca", "cha", "cai", "can", "cen", "san", "shen", "cang", "chen", "zang", "cao", "ce", "ze", "zhai", "ceng", "zha", "chai", "ci", "cuo", "chan", "shan", "xian", "xin", "zhan", "chang", "zhang", "chao", "zhuo", "zhao", "che", "ju", "chuang", "cheng", "dang", "sheng", "deng", "chi", "shi", "chong", "chou", "qiu", "dao", "xiu", "chu", "zhu", "chuai", "tuan", "zhui", "chuo", "zuo", "chuan", "zhuan", "cong", "chui", "chun", "zhun", "zi", "zong", "cou", "zou", "cu", "cuan", "cui", "qi", "cun", "da", "ta", "dai", "tai", "dan", "tan", "tao", "de", "dei", "di", "ti", "tui", "dia", "dian", "tian", "diao", "tiao", "zhou", "die", "she", "ye", "ding", "zheng", "diu", "dong", "tong", "dou", "du", "duo", "duan", "dui", "rui", "yue", "dun", "tun", "tuo", "hui", "wu", "en", "er", "nai", "fa", "fang", "fei", "pei", "fen", "feng", "ping", "fo", "fu", "ga", "jia", "qie", "gai", "ge", "he", "gan", "gang", "jiang", "zhuang", "gao", "hao", "li", "ha", "luo", "gei", "ji", "gen", "hen", "geng", "gong", "zhong", "gou", "kou", "gu", "hu", "gua", "guai", "guan", "guang", "gui", "jun", "xie", "jiong", "jue", "gun", "hun", "guo", "wai", "wo", "ke", "hai", "hei", "hang", "mo", "heng", "peng", "hong", "hou", "xu", "xia", "hua", "huai", "huan", "xun", "huang", "kuai", "qia", "xi", "xue", "jie", "jian", "qian", "nan", "kan", "qiang", "xiang", "jiao", "xiao", "yao", "qiao", "jin", "qin", "jing", "ying", "liang", "jiu", "zui", "qu", "juan", "yun", "qun", "ka", "kai", "kang", "kao", "ken", "keng", "kong", "ku", "kua", "kuan", "kuang", "kui", "kun", "kuo", "la", "lai", "lan", "lang", "lao", "mu", "liao", "le", "lei", "leng", "ling", "zhi", "lia", "lian", "luan", "lu", "lie", "lin", "liu", "lo", "long", "shuang", "lou", "lv", "shuai", "lve", "lun", "ma", "mai", "man", "men", "wan", "mang", "meng", "mao", "mou", "me", "mei", "mi", "si", "mian", "min", "miao", "mie", "nie", "wen", "ming", "miu", "na", "ne", "nei", "nuo", "nang", "nao", "ni", "nen", "neng", "niao", "nian", "niang", "sui", "nin", "ning", "nong", "nou", "nu", "nv", "ru", "nve", "nuan", "re", "o", "ou", "pai", "pao", "pen", "pie", "pou", "se", "yin", "qing", "yan", "sao", "zhen", "qiong", "quan", "xuan", "que", "ran", "rang", "rao", "ren", "reng", "ri", "rong", "rou", "ruan", "run", "ruo", "sa", "sai", "sang", "sen", "seng", "suo", "shai", "shang", "xing", "zhe", "shou", "shu", "shuo", "shua", "shuan", "shui", "shun", "sou", "song", "su", "suan", "sun", "tang", "te", "teng", "tie", "ting", "tou", "tu", "wei", "yuan", "wang", "weng", "zhua", "ei", "yang", "xiong", "you", "yo", "yong", "za", "zan", "zai", "zao", "zei", "zen", "zeng", "zhei", "zhuai", "zu", "zuan", "zun"};
}
